version: '3.2'

services:
    collector:
        build:
            context: .
            dockerfile: collector/Dockerfile
        ports:
            - "12345:12345"
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka

    processor:
        build:
            context: .
            dockerfile: processor/Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka

    kafka:
        image: spotify/kafka
