version: '3.2'

services:
    # for building the base image for all services
    shared:
        build:
            context: .
            dockerfile: shared/Dockerfile
        image: shared

    collector:
        build:
            context: .
            dockerfile: collector/Dockerfile
        ports:
            - "12345:12345"
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka

    span-processor:
        build:
            context: .
            dockerfile: span-processor/Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka

    error-recorder:
        build:
            context: .
            dockerfile: error-recorder/Dockerfile
        restart: on-failure
        depends_on:
            - cassandra
            - kafka
        links:
            - cassandra
            - kafka

    metric-processor:
        build:
            context: .
            dockerfile: metric-processor/Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka

    anomaly-detector:
        build:
            context: .
            dockerfile: anomaly-detector/Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka

    span-recorder:
        build:
            context: .
            dockerfile: span-recorder/Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka
            - cassandra

    trace-selector:
        build:
            context: .
            dockerfile: trace-selector/Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka
            - cassandra

    kafka:
        image: spotify/kafka

    cassandra:
        image: cassandra
