version: '3.2'

services:
    collector:
        build:
            context: .
            dockerfile: collector/Dockerfile
        ports:
            - "12345:12345"
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka

    span-processor:
        build:
            context: .
            dockerfile: span-processor/Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka

    metric-processor:
        build:
            context: .
            dockerfile: metric-processor/Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka

    span-recorder:
        build:
            context: .
            dockerfile: span-recorder/Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        links:
            - kafka
            - cassandra

    kafka:
        image: spotify/kafka

    cassandra:
        image: cassandra
